title: Minimal theme
logo: ![image]https://github.com/Mr-Thiol/mr-thiol.github.io/blob/main/logo_tempo.jpg
description: Sam Sheng@FDU Chemisty
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
