title: Sam Sheng
logo: /assets/img/RR.png
description: · 2020.9 - 2023.6 <br> SHS <br> · 2023.9 - Now <br> Undergraduate Student in Chemistry, Fudan University <br> · ?
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
